"""Initial migration

Revision ID: 7b2dabf57b6d
Revises: 
Create Date: 2026-01-06 21:14:04.245484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2dabf57b6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('email_inboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.Enum('GMAIL', 'OUTLOOK', 'CUSTOM', name='emailprovider'), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DISCONNECTED', 'ERROR', name='inboxstatus'), nullable=False),
    sa.Column('daily_send_limit', sa.Integer(), nullable=True),
    sa.Column('warmup_stage', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_received', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_inboxes_domain'), 'email_inboxes', ['domain'], unique=False)
    op.create_index(op.f('ix_email_inboxes_email_address'), 'email_inboxes', ['email_address'], unique=True)
    op.create_index(op.f('ix_email_inboxes_id'), 'email_inboxes', ['id'], unique=False)
    op.create_table('warmup_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('target_daily_volume', sa.Integer(), nullable=True),
    sa.Column('current_daily_volume', sa.Integer(), nullable=True),
    sa.Column('use_ai_replies', sa.Boolean(), nullable=True),
    sa.Column('reply_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='campaignstatus'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warmup_campaigns_id'), 'warmup_campaigns', ['id'], unique=False)
    op.create_table('campaign_inboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SENDER', 'RECEIVER', 'MIXED', name='inboxrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['warmup_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inbox_id'], ['email_inboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_inboxes_id'), 'campaign_inboxes', ['id'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('from_inbox_id', sa.Integer(), nullable=False),
    sa.Column('to_inbox_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='emaildirection'), nullable=False),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('replied', sa.Boolean(), nullable=True),
    sa.Column('spam_reported', sa.Boolean(), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['warmup_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_inbox_id'], ['email_inboxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_inbox_id'], ['email_inboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False)
    op.create_index(op.f('ix_email_messages_message_id'), 'email_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_email_messages_thread_id'), 'email_messages', ['thread_id'], unique=False)
    op.create_table('reputation_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('emails_received', sa.Integer(), nullable=True),
    sa.Column('emails_opened', sa.Integer(), nullable=True),
    sa.Column('emails_replied', sa.Integer(), nullable=True),
    sa.Column('spam_complaints', sa.Integer(), nullable=True),
    sa.Column('bounce_count', sa.Integer(), nullable=True),
    sa.Column('open_rate', sa.Float(), nullable=True),
    sa.Column('reply_rate', sa.Float(), nullable=True),
    sa.Column('spam_rate', sa.Float(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inbox_id'], ['email_inboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inbox_id', 'date', name='unique_inbox_date')
    )
    op.create_index(op.f('ix_reputation_stats_date'), 'reputation_stats', ['date'], unique=False)
    op.create_index(op.f('ix_reputation_stats_id'), 'reputation_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reputation_stats_id'), table_name='reputation_stats')
    op.drop_index(op.f('ix_reputation_stats_date'), table_name='reputation_stats')
    op.drop_table('reputation_stats')
    op.drop_index(op.f('ix_email_messages_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_campaign_inboxes_id'), table_name='campaign_inboxes')
    op.drop_table('campaign_inboxes')
    op.drop_index(op.f('ix_warmup_campaigns_id'), table_name='warmup_campaigns')
    op.drop_table('warmup_campaigns')
    op.drop_index(op.f('ix_email_inboxes_id'), table_name='email_inboxes')
    op.drop_index(op.f('ix_email_inboxes_email_address'), table_name='email_inboxes')
    op.drop_index(op.f('ix_email_inboxes_domain'), table_name='email_inboxes')
    op.drop_table('email_inboxes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
