"""Add bot email management system

Revision ID: 4bb7627d8b4e
Revises: 7b2dabf57b6d
Create Date: 2026-01-07 23:49:29.093389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4bb7627d8b4e'
down_revision = '7b2dabf57b6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new enum type for bot email status
    op.execute("CREATE TYPE botemailstatus AS ENUM ('ACTIVE', 'PAUSED', 'ERROR', 'DISCONNECTED')")
    
    op.create_table('bot_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('provider', postgresql.ENUM('GMAIL', 'OUTLOOK', 'CUSTOM', name='emailprovider', create_type=False), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('client_secret', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PAUSED', 'ERROR', 'DISCONNECTED', name='botemailstatus', create_type=False), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('total_emails_processed', sa.Integer(), nullable=True),
    sa.Column('spam_moved_to_inbox', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_emails_email_address'), 'bot_emails', ['email_address'], unique=True)
    op.create_index(op.f('ix_bot_emails_id'), 'bot_emails', ['id'], unique=False)
    op.create_table('bot_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_email_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('was_in_spam', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_email_id'], ['bot_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_activities_id'), 'bot_activities', ['id'], unique=False)
    op.create_table('user_bot_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_email_id', sa.Integer(), nullable=False),
    sa.Column('user_email_address', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('check_spam', sa.Boolean(), nullable=True),
    sa.Column('auto_report_not_spam', sa.Boolean(), nullable=True),
    sa.Column('emails_received', sa.Integer(), nullable=True),
    sa.Column('emails_in_spam', sa.Integer(), nullable=True),
    sa.Column('spam_reports_made', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_email_id'], ['bot_emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bot_email_id', 'user_email_address', name='unique_user_bot_assignment')
    )
    op.create_index(op.f('ix_user_bot_assignments_id'), 'user_bot_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bot_assignments_id'), table_name='user_bot_assignments')
    op.drop_table('user_bot_assignments')
    op.drop_index(op.f('ix_bot_activities_id'), table_name='bot_activities')
    op.drop_table('bot_activities')
    op.drop_index(op.f('ix_bot_emails_id'), table_name='bot_emails')
    op.drop_index(op.f('ix_bot_emails_email_address'), table_name='bot_emails')
    op.drop_table('bot_emails')
    # ### end Alembic commands ###
