"""add_cross_account_protection_tables

Revision ID: a9dd63838012
Revises: 2f707dfb2473
Create Date: 2026-01-19 22:13:56.671705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dd63838012'
down_revision = '2f707dfb2473'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create security_event_logs table
    op.create_table('security_event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('TOKEN_REVOKED', 'ACCOUNT_DISABLED', 'ACCOUNT_ENABLED', 'ACCOUNT_PURGED', 'CREDENTIAL_CHANGE', 'SESSIONS_REVOKED', name='securityeventtype'), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=True),
    sa.Column('user_inboxes_affected', sa.Integer(), nullable=True),
    sa.Column('bot_emails_affected', sa.Integer(), nullable=True),
    sa.Column('raw_event_token', sa.Text(), nullable=True),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('reauthentication_required', sa.Boolean(), nullable=True),
    sa.Column('event_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_event_logs_event_type'), 'security_event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_event_logs_id'), 'security_event_logs', ['id'], unique=False)
    op.create_index(op.f('ix_security_event_logs_subject_email'), 'security_event_logs', ['subject_email'], unique=False)
    
    # Create reauthentication_requests table
    op.create_table('reauthentication_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('security_event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reauth_url', sa.Text(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['security_event_id'], ['security_event_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reauthentication_requests_email_address'), 'reauthentication_requests', ['email_address'], unique=False)
    op.create_index(op.f('ix_reauthentication_requests_id'), 'reauthentication_requests', ['id'], unique=False)
    
    # Only apply safe changes - skip problematic column alterations
    # Skip: op.alter_column('bot_emails', 'watch_expiration', ...)
    # Skip: op.alter_column('email_messages', 'to_inbox_id', ...)
    # Skip: op.alter_column('email_messages', 'is_bot_reply', ...)
    
    # Create index on system_settings (safe operation)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    
    # Skip: op.alter_column('warmup_campaigns', 'use_bot_system', ...)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warmup_campaigns', 'use_bot_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.alter_column('email_messages', 'is_bot_reply',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'to_inbox_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bot_emails', 'watch_expiration',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_reauthentication_requests_id'), table_name='reauthentication_requests')
    op.drop_index(op.f('ix_reauthentication_requests_email_address'), table_name='reauthentication_requests')
    op.drop_table('reauthentication_requests')
    op.drop_index(op.f('ix_security_event_logs_subject_email'), table_name='security_event_logs')
    op.drop_index(op.f('ix_security_event_logs_id'), table_name='security_event_logs')
    op.drop_index(op.f('ix_security_event_logs_event_type'), table_name='security_event_logs')
    op.drop_table('security_event_logs')
    # ### end Alembic commands ###
